version: '3.8'

services:

  # ห้องที่ 1: PHP (รันโค้ด Laravel)
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel_net

  # ห้องที่ 2: Nginx (Web Server)
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"      # เปิด port 8080 ให้เข้าจาก browser ได้
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

  # ห้องที่ 3: MySQL (ฐานข้อมูล)
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel_user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  db_data: